In [12]:
import pandas as pd

# df = pd.read_csv('MinimumWageData.csv', encoding="latin")
# df.to_csv('minwage.csv', encoding="utf-8")

df = pd.read_csv('minwage.csv', encoding="utf-8")
df.head()

,Unnamed: 0,Year,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,0,1968,Alabama,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
1,1,1968,Alaska,2.10,NaN,2.10000,2.10000,34.783333,15.12,15.12
2,2,1968,Arizona,18.72 - 26.40/wk(b),(b),0.66000,0.46800,34.783333,4.75,3.37
3,3,1968,Arkansas,1.25/day(b),(b),0.15625,0.15625,34.783333,1.12,1.12
4,4,1968,California,1.65(b),(b),1.65000,1.65000,34.783333,11.88,11.88

In [18]:
gb = df.groupby('State')
gb.get_group('Alabama').set_index('Year').head()

,Unnamed: 0,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
Year,,,,,,,,,
1968,0,Alabama,...,NaN,0.0,0.0,34.783333,0.0,0.0
1969,55,Alabama,...,NaN,0.0,0.0,36.683333,0.0,0.0
1970,110,Alabama,...,NaN,0.0,0.0,38.825000,0.0,0.0
1971,165,Alabama,...,NaN,0.0,0.0,40.491667,0.0,0.0
1972,220,Alabama,...,NaN,0.0,0.0,41.816667,0.0,0.0

In [39]:
act_min_wage = pd.DataFrame()

for name, group in df.groupby("State"):
    if act_min_wage.empty:
        act_min_wage = group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name})
    else:
        act_min_wage = act_min_wage.join(group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name}))

act_min_wage

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Year,,,,,,,,,,,,,,,,,,,,,
1968,0.0,15.12,3.37,1.12,11.88,7.20,10.08,9.00,9.00,8.28,...,0.0,0.00,NaN,7.20,10.08,0.00,11.52,7.20,9.00,8.64
1969,0.0,14.33,3.19,1.07,11.26,6.83,9.56,8.53,8.53,7.85,...,0.0,0.00,NaN,6.83,9.56,0.00,10.92,6.83,8.53,8.19
1970,0.0,13.54,3.02,7.09,10.64,6.45,10.32,8.06,10.32,8.38,...,0.0,0.00,NaN,6.45,10.32,0.00,10.32,6.45,8.38,8.38
1971,0.0,12.99,2.89,6.80,10.20,6.18,9.89,7.73,9.89,8.04,...,0.0,0.00,NaN,6.18,9.89,0.00,9.89,6.18,8.04,8.04
1972,0.0,12.57,2.80,7.19,9.88,5.99,11.08,9.58,9.58,9.58,...,0.0,8.38,NaN,7.19,9.58,0.00,9.58,7.19,8.68,8.98
1973,0.0,11.84,2.64,6.77,9.31,5.64,10.43,9.02,9.02,9.02,...,0.0,7.90,NaN,6.77,9.02,0.00,9.02,6.77,8.18,8.46
1974,0.0,10.66,2.38,6.09,8.38,5.08,9.39,8.13,8.13,8.13,...,0.0,7.11,NaN,6.09,8.13,0.00,8.13,6.09,7.36,7.62
1975,0.0,9.77,2.18,5.58,7.68,4.65,8.61,7.44,7.44,7.44,...,0.0,6.51,NaN,5.58,7.44,0.00,7.44,5.58,6.75,6.98
1976,0.0,12.32,0.00,8.36,8.80,4.40,9.72,8.80,9.90,9.68,...,0.0,6.16,NaN,6.82,10.12,8.80,9.68,8.80,9.24,7.04
1977,0.0,11.57,0.00,7.85,8.26,4.13,9.13,8.26,9.30,9.09,...,0.0,5.78,NaN,6.40,9.50,8.26,9.09,8.26,8.68,6.61
1978,0.0,10.75,0.00,7.29,7.68,3.84,8.48,7.68,8.64,8.44,...,0.0,5.37,NaN,5.95,8.83,7.68,8.44,7.68,8.06,6.14
1979,0.0,11.73,0.00,7.94,10.01,6.56,10.04,6.90,8.49,10.01,...,0.0,4.83,10.01,7.59,10.01,8.11,7.94,7.59,9.66,5.52
1980,0.0,10.94,0.00,7.75,8.81,5.77,9.48,6.08,7.60,9.42,...,0.0,4.25,9.42,7.14,9.42,7.14,6.99,6.68,9.12,4.86
1981,0.0,10.60,0.00,7.44,9.23,5.23,9.28,5.51,6.88,9.23,...,0.0,3.86,9.23,6.88,9.23,7.30,6.33,7.57,8.95,4.41
1982,0.0,9.99,0.00,7.01,8.69,4.93,8.74,5.19,6.49,8.69,...,0.0,3.63,8.69,6.49,8.69,6.88,5.97,7.14,8.43,4.15
1983,0.0,9.68,0.00,6.79,8.42,4.78,8.47,5.03,6.29,8.42,...,0.0,3.52,8.42,6.29,8.42,6.66,5.78,6.91,8.17,4.02
1984,0.0,9.28,0.00,6.51,8.07,4.58,8.12,4.82,6.03,8.07,...,0.0,3.37,8.07,6.03,8.07,6.39,5.54,6.63,7.83,3.86
1985,0.0,8.96,0.00,6.29,7.80,4.42,7.84,4.66,5.82,7.80,...,0.0,3.26,7.80,5.82,7.80,6.17,5.35,6.40,7.57,3.72
1986,0.0,8.80,0.00,6.17,7.65,4.34,7.70,4.57,5.71,7.65,...,0.0,3.20,7.65,5.71,7.65,6.05,5.25,6.28,7.42,3.66
1987,0.0,8.48,0.00,5.95,7.38,4.19,7.43,4.41,5.51,7.38,...,0.0,3.09,7.38,5.51,7.38,5.84,5.07,6.06,7.16,3.53
1988,0.0,8.15,0.00,6.88,7.09,6.35,7.94,7.09,7.41,7.09,...,0.0,7.09,7.09,5.29,7.52,5.61,4.87,7.09,7.09,3.39
1989,0.0,7.78,0.00,6.56,6.77,6.06,7.57,6.77,7.07,6.77,...,0.0,6.77,6.77,5.05,7.17,5.35,4.65,6.77,6.77,3.23
1990,0.0,7.38,0.00,6.23,6.42,5.75,7.19,6.42,6.71,6.42,...,0.0,6.42,6.42,4.79,6.80,5.08,4.41,6.42,6.42,3.07
1991,0.0,7.91,0.00,6.16,7.81,5.52,7.81,6.99,6.80,6.99,...,0.0,6.16,8.55,6.99,7.08,4.87,7.81,6.16,6.99,2.94
1992,0.0,8.48,0.00,6.51,7.58,5.35,7.62,7.58,6.96,7.58,...,0.0,5.98,8.30,7.58,7.58,6.51,7.58,6.78,6.78,2.86
1993,0.0,8.23,0.00,6.33,7.37,5.20,7.40,7.37,6.76,7.37,...,0.0,5.81,8.06,7.37,7.37,6.33,7.37,6.59,6.59,2.77
1994,0.0,8.02,0.00,7.18,7.18,5.07,7.21,7.18,7.18,7.18,...,0.0,5.66,7.86,7.18,7.18,7.18,7.18,7.18,7.18,2.70
1995,0.0,7.81,0.00,6.98,6.98,4.93,7.02,6.98,6.98,6.98,...,0.0,5.50,7.64,6.98,6.98,6.98,6.98,6.98,6.98,2.63
1996,0.0,7.58,0.00,6.78,6.78,4.79,6.82,7.42,8.38,6.78,...,0.0,5.35,7.42,6.78,7.58,6.78,7.82,6.78,6.78,2.55
1997,0.0,8.19,0.00,6.63,7.41,7.41,7.44,7.80,8.97,7.41,...,0.0,5.23,7.25,7.41,7.80,7.41,7.64,6.63,7.41,2.50
1998,0.0,8.68,0.00,7.91,7.91,7.91,7.96,7.91,9.45,7.91,...,0.0,5.15,7.14,7.91,8.06,7.91,7.53,7.30,7.91,2.46
1999,0.0,8.49,0.00,7.74,7.74,7.74,7.79,7.74,9.24,7.74,...,0.0,5.04,6.99,7.74,7.89,7.74,7.37,7.14,7.74,2.41
2000,0.0,8.22,0.00,7.49,8.36,7.49,8.94,8.22,8.94,7.49,...,0.0,4.87,6.25,7.49,8.36,7.49,9.45,7.49,7.49,2.33
2001,0.0,7.99,0.00,7.28,8.84,7.28,9.05,8.70,8.70,7.28,...,0.0,4.74,6.08,7.28,8.84,7.28,9.50,7.28,7.28,2.26
2002,0.0,7.87,0.00,7.17,9.40,7.17,9.33,8.56,8.56,7.17,...,0.0,7.17,5.99,7.17,8.70,7.17,9.61,7.17,7.17,7.17
2003,0.0,9.73,0.00,7.01,9.19,7.01,9.39,8.37,8.37,7.01,...,0.0,7.01,5.85,7.01,8.51,7.01,9.54,7.01,7.01,7.01
2004,0.0,9.48,0.00,6.83,8.95,6.83,9.41,8.15,8.15,6.83,...,0.0,6.83,5.70,6.83,8.95,6.83,9.49,6.83,6.83,6.83
2005,0.0,9.17,0.00,6.60,8.65,6.60,9.10,7.89,8.46,6.60,...,0.0,6.60,5.51,6.60,8.98,6.60,9.42,6.60,6.60,6.60
2006,0.0,8.88,0.00,6.40,8.38,6.40,9.19,7.64,8.69,6.40,...,0.0,6.40,5.34,6.40,9.01,6.40,9.48,6.40,7.08,6.40
2007,0.0,8.63,8.15,7.55,9.06,8.27,9.24,8.03,8.45,6.22,...,0.0,6.22,5.19,6.22,9.09,6.22,9.58,7.06,7.85,6.22
2008,0.0,8.32,8.02,7.27,9.30,8.16,8.90,8.32,8.14,6.80,...,0.0,6.80,5.00,6.80,8.93,6.80,9.39,7.62,7.56,5.99
2009,0.0,8.35,8.46,7.29,9.34,8.50,9.34,8.35,8.81,7.64,...,0.0,7.64,5.02,7.64,9.41,7.64,9.98,8.46,7.59,6.01
2010,0.0,8.90,8.33,7.18,9.19,8.31,9.47,8.33,9.47,8.33,...,0.0,8.33,4.94,8.33,9.26,8.33,9.82,8.33,8.33,5.91
2011,0.0,8.63,8.18,6.96,8.91,8.19,9.18,8.07,9.18,8.07,...,0.0,8.07,4.79,8.07,9.07,8.07,9.65,8.07,8.07,5.73
2012,0.0,8.45,8.34,6.82,8.72,8.33,9.00,7.91,9.00,7.91,...,0.0,7.91,4.69,7.91,9.23,7.91,9.86,7.91,7.91,5.62
2013,0.0,8.33,8.38,6.72,8.60,8.36,8.87,7.79,8.87,7.79,...,0.0,7.79,4.62,7.79,9.24,7.79,9.88,7.79,7.79,5.54
2014,0.0,8.20,8.36,6.61,9.52,8.46,9.20,8.20,10.05,7.67,...,0.0,7.67,4.55,7.67,9.23,7.67,9.86,7.67,7.67,5.45
2015,0.0,9.24,8.50,7.92,9.51,8.69,9.67,8.72,11.09,7.66,...,0.0,7.66,4.54,7.66,9.67,7.66,10.00,8.45,7.66,5.44
2016,0.0,10.17,8.40,8.35,10.43,8.67,10.02,8.61,12.00,7.56,...,0.0,7.56,4.49,7.56,10.02,7.56,9.88,9.13,7.56,5.37
2017,0.0,10.01,10.22,8.68,10.22,9.50,10.32,8.43,11.75,7.41,...,0.0,7.41,4.39,7.41,10.22,7.41,11.24,8.94,7.41,5.26